services:
  agenttheo:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        BROWSER: ${BROWSER:-chromium}
        PYTHON_VERSION: ${PYTHON_VERSION:-3.11}
        NODE_VERSION: ${NODE_VERSION:-20}
    image: agenttheo:latest
    container_name: agenttheo
    env_file:
      - ../config/.env
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - BROWSER=${BROWSER:-chromium}
      - DISPLAY=:1
    volumes:
      - ../logs:/app/logs
      - ../config:/app/config:ro
    init: true
    ipc: host
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    stdin_open: true
    tty: true
    ports:
      - "5901:5901"  # VNC port
      - "6080:6080"  # noVNC web interface
      - "8000:8000"  # AgentTheo Web UI