services:
  agenttheo:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - DOCKER_BUILDKIT=1
    image: agenttheo:latest
    container_name: agenttheo
    env_file:
      - ../config/.env
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - BROWSER=${BROWSER:-chromium}
      - DISPLAY=:1
    volumes:
      - ../logs:/app/logs
      - ../config:/app/config:ro
      # Development volumes - mount source code for hot reload
      - ../agent:/app/agent:ro
      - ../webui:/app/webui:ro
      - ../entrypoint.py:/app/entrypoint.py:ro
    init: true
    ipc: host
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_ADMIN
    stdin_open: true
    tty: true
    ports:
      - "5901:5901"  # VNC port
      - "6080:6080"  # noVNC web interface
      - "8000:8000"  # AgentTheo Web UI